language: ruby
rvm:
  - 2.2.1

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
